#!/usr/bin/env python

"""Nested radial + Er scan (scanType=5).

Called by ``sfincsScan`` when ``!ss scanType = 5``. Uses ``profiles`` to set
plasma profiles, then launches an Er scan at each radius.
"""

# This script will not work if called directly.
# From the command line, you should call sfincsScan instead.

profilesFilename = 'profiles'

import os, inspect
import sys
import subprocess
from pathlib import Path
from builtins import input

#print ("This is "+ inspect.getfile(inspect.currentframe()))
this_filename = "sfincsScan_5"
print ("This is "+ this_filename)
print ("Beginning a scan of Er inside a scan over radius.")

# Determine radii to use, and n & T at those radii:
skipExistingDirectories = False
#execfile(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))+"/radialScans")
exec(open(os.path.dirname(os.path.abspath(__file__))+"/radialScans").read())

if waitBeforeSubmitting:
    while True:
        #proceed=raw_input("Should I go ahead and launch Er scans at these "+str(len(radii))+" radii? [y/n] ")
        proceed=input("Should I go ahead and launch Er scans at these "+str(len(radii))+" radii? [y/n] ")
        if proceed=="y" or proceed=="n":
            break
        print ("You must enter either y or n.")

    if proceed=="n":
        exit(0)

print ("launching runs...")

base_dir = os.getcwd()
prev_dir = None

for runNum in range(len(radii)):
    directory = directories[runNum]
    print ("Beginning to handle radius "+str(runNum+1)+" of "+str(len(radii))+": "+directory)

    # To be extra safe, check again to see if the directory exists.
    if os.path.exists(directory):
        print ("Directory "+directory+" already exists.")
    else:
        print ("Creating directory "+directory)
        os.makedirs(directory)
    os.chdir(directory)
    work_dir = os.getcwd()
    current_dir = Path(work_dir)
    configure_krylov_recycle(prev_dir, current_dir)

    # Now copy the input.namelist file:

    input_lines = []
    for line in inputFile:
        # Set sfincsScan directives:
        if namelistLineContainsSS(line,"scanType"):
##            line = "!ss scanType = 2  ! set by sfincsScan_5.\n"
            continue
        if namelistLineContainsSS(line,"NErs"):
##            line = "!ss NErs = "+str(int(NErs[runNum]))+"  ! set by sfincsScan_5.\n"
            continue
        if namelistLineContainsSS(line,generalErName+"Max"):
##            line = "!ss dPhiHatd"+radiusNameForGradients+"Max = "+str(dPhiHatdradius_max[runNum])+"  ! set by sfincsScan_5.\n"
            continue
        if namelistLineContainsSS(line,generalErName+"Min"):
##            line = "!ss dPhiHatd"+radiusNameForGradients+"Min = "+str(dPhiHatdradius_min[runNum])+"  ! set by sfincsScan_5.\n"
            continue
        # Now set fortran variables:
        if namelistLineContains(line,radiusName+"_wish"):
##            line = "  "+radiusName+"_wish = "+str(radii[runNum])+" ! Set by sfincsScan_5.\n"
            continue
        if namelistLineContains(line,"nHats"):
##            line = "  nHats ="
##            for ispecies in range(Nspecies):
##                line += " "+str(nHats[ispecies][runNum])
##            line += " ! Set by sfincsScan_5.\n"
            continue
        if namelistLineContains(line,"dnHatd"+radiusNameForGradients+"s"):
##            line = "  dnHatd"+radiusNameForGradients+"s ="
##            for ispecies in range(Nspecies):
##                line += " "+str(dnHatdradii[ispecies][runNum])
##            line += " ! Set by sfincsScan_5.\n"
            continue
        if namelistLineContains(line,"THats"):
##            line = "  THats ="
##            for ispecies in range(Nspecies):
##                line += " "+str(THats[ispecies][runNum])
##            line += " ! Set by sfincsScan_5.\n"
            continue
        if namelistLineContains(line,"dTHatd"+radiusNameForGradients+"s"):
##            line = "  dTHatd"+radiusNameForGradients+"s ="
##            for ispecies in range(Nspecies):
##                line += " "+str(dTHatdradii[ispecies][runNum])
##            line += " ! Set by sfincsScan_5.\n"
            continue

        if line.strip().find("&geometryParameters") == 0 :
            line += "  "+radiusName+"_wish = "+str(radii[runNum])+" ! Set by sfincsScan_5.\n"

        if line.strip().find("&speciesParameters") == 0 :
            line += "  nHats =" 
            for ispecies in range(Nspecies):
                line += " "+str(nHats[ispecies][runNum])
            line += " ! Set by sfincsScan_5.\n"    

            line += "  dnHatd"+radiusNameForGradients+"s ="
            for ispecies in range(Nspecies):
                line += " "+str(dnHatdradii[ispecies][runNum])
            line += " ! Set by sfincsScan_5.\n"

            line += "  THats ="
            for ispecies in range(Nspecies):
                line += " "+str(THats[ispecies][runNum])
            line += " ! Set by sfincsScan_5.\n"

            line += "  dTHatd"+radiusNameForGradients+"s ="
            for ispecies in range(Nspecies):
                line += " "+str(dTHatdradii[ispecies][runNum])
            line += " ! Set by sfincsScan_5.\n"    

        #######################    
        input_lines.append(line)

    line = "!ss scanType = 2  ! set by sfincsScan_5.\n"
    line += "!ss NErs = "+str(int(NErs[runNum]))+"  ! set by sfincsScan_5.\n"
    line += "!ss "+generalErName+"Max = "+str(generalEr_max[runNum])+"  ! set by sfincsScan_5.\n"
    line += "!ss "+generalErName+"Min = "+str(generalEr_min[runNum])+"  ! set by sfincsScan_5.\n"
    input_lines.append(line)

    input_path = Path(filename)
    input_path.write_text("".join(input_lines))

    #################################################

    # Submit the Er scan:
##    submitCommand = "sfincsScan -f" 
    #submitCommand = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))+"/sfincsScan -f"
    submitCommand = [sys.executable, str(Path(__file__).resolve().with_name("sfincsScan")), "--yes", "--input", str(input_path)]
    subprocess.call(submitCommand, cwd=work_dir)

    os.chdir(base_dir)
    prev_dir = current_dir
