#!/usr/bin/env python
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import sys
from typing import Any, Dict, List, Tuple

import numpy as np

_REPO_ROOT = Path(__file__).resolve().parents[1]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from sfincs_jax.io import sfincs_jax_output_dict
from sfincs_jax.namelist import read_sfincs_input
from sfincs_jax.v3 import geometry_from_namelist, grids_from_namelist


def _get_int(group: Dict[str, Any], key: str, default: int | None = None) -> int | None:
    v = group.get(key.upper(), default)
    if v is None:
        return None
    return int(v)


def _get_bool(group: Dict[str, Any], key: str, default: bool = False) -> bool:
    return bool(group.get(key.upper(), default))


def _get_nspecies(species_group: Dict[str, Any]) -> int | None:
    z = species_group.get("ZS")
    if z is None:
        return None
    if isinstance(z, (list, tuple, np.ndarray)):
        return int(len(z))
    return 1


@dataclass(frozen=True)
class ExampleRow:
    name: str
    relpath: str
    geometry_scheme: int | None
    n_species: int | None
    collision_operator: int | None
    include_phi1: bool
    include_xdot: bool
    include_er_xidot: bool
    use_dkes_exb: bool
    magnetic_drift_scheme: int | None
    sfincs_jax_support: str


def classify_support(input_path: Path) -> Tuple[str, ExampleRow]:
    nml = read_sfincs_input(input_path)
    geom = nml.group("geometryParameters")
    phys = nml.group("physicsParameters")
    species = nml.group("speciesParameters")

    geometry_scheme = _get_int(geom, "geometryScheme")
    n_species = _get_nspecies(species)
    collision_operator = _get_int(phys, "collisionOperator")
    include_phi1 = _get_bool(phys, "includePhi1", False)
    include_xdot = _get_bool(phys, "includeXDotTerm", False)
    include_er_xidot = _get_bool(phys, "includeElectricFieldTermInXiDot", False)
    use_dkes_exb = _get_bool(phys, "useDKESExBDrift", False)
    magnetic_drift_scheme = _get_int(phys, "magneticDriftScheme")

    support = "unsupported"
    try:
        grids = grids_from_namelist(nml)
    except Exception as e:  # noqa: BLE001
        support = f"grids: fail ({type(e).__name__})"
        grids = None
    if grids is not None:
        support = "grids only"
        try:
            _ = geometry_from_namelist(nml=nml, grids=grids)
            support = "grids+geometry"
        except Exception:  # noqa: BLE001
            pass
        if support == "grids+geometry":
            try:
                _ = sfincs_jax_output_dict(nml=nml, grids=grids)
                support = "write-output"
            except Exception:  # noqa: BLE001
                pass

    row = ExampleRow(
        name=input_path.parent.name,
        relpath=str(input_path.parent),
        geometry_scheme=geometry_scheme,
        n_species=n_species,
        collision_operator=collision_operator,
        include_phi1=include_phi1,
        include_xdot=include_xdot,
        include_er_xidot=include_er_xidot,
        use_dkes_exb=use_dkes_exb,
        magnetic_drift_scheme=magnetic_drift_scheme,
        sfincs_jax_support=support,
    )
    return support, row


def _rst_escape(s: str) -> str:
    return s.replace("`", "``")


def write_rst_table(rows: List[ExampleRow], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Summary stats:
    total = len(rows)
    by_support: Dict[str, int] = {}
    by_geom: Dict[int | None, int] = {}
    for r in rows:
        by_support[r.sfincs_jax_support] = by_support.get(r.sfincs_jax_support, 0) + 1
        by_geom[r.geometry_scheme] = by_geom.get(r.geometry_scheme, 0) + 1

    def _fmt_geom(k: int | None) -> str:
        return "unknown" if k is None else str(k)

    support_lines = ", ".join(f"{k}={v}" for k, v in sorted(by_support.items(), key=lambda kv: (-kv[1], kv[0])))
    geom_lines = ", ".join(f"{_fmt_geom(k)}={v}" for k, v in sorted(by_geom.items(), key=lambda kv: (str(kv[0]),)))

    lines: List[str] = []
    lines.append(".. NOTE: This file is auto-generated by `scripts/generate_fortran_example_audit.py`.\n\n")
    lines.append(f"- Total examples scanned: **{total}**\n")
    lines.append(f"- By `sfincs_jax` support: {support_lines}\n")
    lines.append(f"- By `geometryScheme`: {geom_lines}\n")
    lines.append("\n")

    lines.append(".. list-table:: Fortran v3 example inputs (audit)\n")
    lines.append("   :header-rows: 1\n")
    lines.append("   :widths: 26 10 7 9 7 7 7 9 10\n")
    lines.append("\n")
    header = [
        "Example",
        "geometryScheme",
        "Nspecies",
        "collisionOp",
        "Phi1",
        "xDot",
        "Er-xiDot",
        "DKES ExB",
        "`sfincs_jax`",
    ]
    lines.append("   * - " + "\n     - ".join(header) + "\n")

    def b(x: bool) -> str:
        return "yes" if x else "no"

    for r in sorted(rows, key=lambda rr: rr.name):
        row_vals = [
            _rst_escape(r.name),
            _rst_escape("" if r.geometry_scheme is None else str(r.geometry_scheme)),
            _rst_escape("" if r.n_species is None else str(r.n_species)),
            _rst_escape("" if r.collision_operator is None else str(r.collision_operator)),
            b(r.include_phi1),
            b(r.include_xdot),
            b(r.include_er_xidot),
            b(r.use_dkes_exb),
            _rst_escape(r.sfincs_jax_support),
        ]
        lines.append("   * - " + "\n     - ".join(row_vals) + "\n")

    out_path.write_text("".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate a docs table auditing Fortran v3 example inputs.")
    ap.add_argument(
        "--examples-root",
        type=Path,
        default=Path(__file__).resolve().parents[2] / "sfincs" / "fortran" / "version3" / "examples",
        help="Path to SFINCS Fortran v3 examples directory.",
    )
    ap.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "docs" / "_generated" / "fortran_examples_table.rst",
        help="Output RST file path (included by Sphinx).",
    )
    args = ap.parse_args()

    examples_root: Path = args.examples_root
    if not examples_root.exists():
        raise SystemExit(f"examples root does not exist: {examples_root}")

    rows: List[ExampleRow] = []
    for input_path in sorted(examples_root.rglob("input.namelist")):
        _support, row = classify_support(input_path)
        rows.append(row)

    write_rst_table(rows, args.out)
    print(f"Wrote {args.out} ({len(rows)} examples).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
